In [ ]:
import numpy as np
import pandas as pd

In [ ]:
train_data = np.loadtxt("https://files.codingninjas.in/0000000000002419_training_ccpp_x_y_train-7050.csv", delimiter=",")
x = train_data[:,:-1]
y = train_data[:,-1]
x

array([[   8.58,   38.38, 1021.03,   84.37],
       [  21.79,   58.2 , 1017.21,   66.74],
       [  16.64,   48.92, 1011.55,   78.76],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74],
       [  16.37,   54.3 , 1017.94,   63.63],
       [  30.11,   62.04, 1010.69,   47.96]])

In [ ]:
li = ['x1','x2','x3','x4']
df = pd.DataFrame(x)
df.columns = li
df

x1     x2       x3     x4
0      8.58  38.38  1021.03  84.37
1     21.79  58.20  1017.21  66.74
2     16.64  48.92  1011.55  78.76
3     31.38  71.32  1009.17  60.42
4      9.20  40.03  1017.05  92.46
...     ...    ...      ...    ...
7171   9.32  37.73  1022.14  79.49
7172  11.20  41.38  1021.65  61.89
7173  29.80  69.34  1009.36  64.74
7174  16.37  54.30  1017.94  63.63
7175  30.11  62.04  1010.69  47.96

[7176 rows x 4 columns]

In [ ]:
for i in range(4):
    for j in range(i, 4):
        ele = li[i] + "_" + li[j]
        df[ele] = df[li[i]]*df[li[j]]
df

x1     x2       x3     x4     x1_x1      x1_x2       x1_x3  \
0      8.58  38.38  1021.03  84.37   73.6164   329.3004   8760.4374   
1     21.79  58.20  1017.21  66.74  474.8041  1268.1780  22165.0059   
2     16.64  48.92  1011.55  78.76  276.8896   814.0288  16832.1920   
3     31.38  71.32  1009.17  60.42  984.7044  2238.0216  31667.7546   
4      9.20  40.03  1017.05  92.46   84.6400   368.2760   9356.8600   
...     ...    ...      ...    ...       ...        ...         ...   
7171   9.32  37.73  1022.14  79.49   86.8624   351.6436   9526.3448   
7172  11.20  41.38  1021.65  61.89  125.4400   463.4560  11442.4800   
7173  29.80  69.34  1009.36  64.74  888.0400  2066.3320  30078.9280   
7174  16.37  54.30  1017.94  63.63  267.9769   888.8910  16663.6778   
7175  30.11  62.04  1010.69  47.96  906.6121  1868.0244  30431.8759   

          x1_x4      x2_x2       x2_x3      x2_x4         x3_x3       x3_x4  \
0      723.8946  1473.0244  39187.1314  3238.1206  1.042502e+06  86144.3011   
1     1454.2646  3387.2400  59201.6220  3884.2680  1.034716e+06  67888.5954   
2     1310.5664  2393.1664  49485.0260  3852.9392  1.023233e+06  79669.6780   
3     1895.9796  5086.5424  71974.0044  4309.1544  1.018424e+06  60974.0514   
4      850.6320  1602.4009  40712.5115  3701.1738  1.034391e+06  94036.4430   
...         ...        ...         ...        ...           ...         ...   
7171   740.8468  1423.5529  38565.3422  2999.1577  1.044770e+06  81249.9086   
7172   693.1680  1712.3044  42275.8770  2561.0082  1.043769e+06  63229.9185   
7173  1929.2520  4808.0356  69989.0224  4489.0716  1.018808e+06  65345.9664   
7174  1041.6231  2948.4900  55274.1420  3455.1090  1.036202e+06  64771.5222   
7175  1444.0756  3848.9616  62703.2076  2975.4384  1.021494e+06  48472.6924   

          x4_x4  
0     7118.2969  
1     4454.2276  
2     6203.1376  
3     3650.5764  
4     8548.8516  
...         ...  
7171  6318.6601  
7172  3830.3721  
7173  4191.2676  
7174  4048.7769  
7175  2300.1616  

[7176 rows x 14 columns]

In [ ]:
import numpy as np
data = np.loadtxt("https://files.codingninjas.in/data-6984.csv", delimiter=",")
data.shape

(100, 2)

In [ ]:
training_data = data[:70,:]
training_data.shape

(70, 2)

In [ ]:
testing_data = data[70:,]
testing_data.shape

(30, 2)

In [ ]:
def step_gradient(points, learning_rate, m , c):
    m_slope = 0
    c_slope = 0
    M = len(points)
    for i in range(M):
        x = points[i, 0]
        y = points[i, 1]
        m_slope += (-2/M)* (y - m * x - c)*x
        c_slope += (-2/M)* (y - m * x - c)
    new_m = m - learning_rate * m_slope
    new_c = c - learning_rate * c_slope
    return new_m, new_c

In [ ]:
# The Gradient Descent Function
def gd(points, learning_rate, num_iterations):
    m = 0       # Intial random value taken as 0
    c = 0       # Intial random value taken as 0
    for i in range(num_iterations):
        m, c = step_gradient(points, learning_rate, m , c)
        print(i, " Cost: ", cost(points, m, c))
    return m, c

In [ ]:
# This function finds the new cost after each optimisation.
def cost(points, m, c):
    total_cost = 0
    M = len(points)
    for i in range(M):
        x = points[i, 0]
        y = points[i, 1]
        total_cost += (1/M)*((y - m*x - c)**2)
    return total_cost

In [ ]:
def run():
    learning_rate = 0.0001
    num_iterations = 100
    m, c = gd(training_data, learning_rate, num_iterations)
    print("Final m :", m)
    print("Final c :", c)
    return m,c

In [ ]:
m, c = run()

0  Cost:  1461.4044104341087
1  Cost:  460.8670268567474
2  Cost:  205.4870778024464
3  Cost:  140.30318108579826
4  Cost:  123.66545280139864
5  Cost:  119.41878332450108
6  Cost:  118.33484209854512
7  Cost:  118.05816441204072
8  Cost:  117.98753491264765
9  Cost:  117.96949772470519
10  Cost:  117.96488434447647
11  Cost:  117.96369729432573
12  Cost:  117.96338479030575
13  Cost:  117.96329550799736
14  Cost:  117.9632632015475
15  Cost:  117.9632454379033
16  Cost:  117.96323138633423
17  Cost:  117.96321828237488
18  Cost:  117.96320542041524
19  Cost:  117.96319262035338
20  Cost:  117.9631798362198
21  Cost:  117.96316705628094
22  Cost:  117.96315427754192
23  Cost:  117.96314149923846
24  Cost:  117.96312872117527
25  Cost:  117.96311594330255
26  Cost:  117.9631031656078
27  Cost:  117.9630903880875
28  Cost:  117.96307761074107
29  Cost:  117.96306483356811
30  Cost:  117.96305205656859
31  Cost:  117.96303927974257
32  Cost:  117.96302650309
33  Cost:  117.96301372661085


In [ ]:
def predict(final_m, final_c, testing_data):
    y_pred = []
    for i in range(len(testing_data)):
        ans = m*testing_data[i][0] + c
        y_pred.append(ans)
    return y_pred

In [ ]:
y_pred = predict(m, c, testing_data)
y_pred

[46.095951282291885,
 78.28376167276944,
 68.10702680868928,
 62.8946250628685,
 102.61496837133335,
 64.91436131908361,
 83.8887150992528,
 53.885894749919025,
 81.41143026364702,
 56.838414234095204,
 83.00892226345628,
 82.96180012666355,
 50.09887462980676,
 86.14202346395936,
 84.30240868699974,
 79.18991662796913,
 74.5328181331299,
 73.35763378901311,
 64.50442501659097,
 55.45411963583681,
 48.06804235977706,
 78.32854078411849,
 100.31042647345949,
 67.44897116945312,
 99.65949980894587,
 72.98918795613403,
 71.83656946861555,
 73.00289789301861,
 70.24720708812089,
 36.67615508488324]

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor()
x_train = training_data[:,0].reshape(-1, 1)
y_train = training_data[:,1]
model.fit(x_train,y_train)

GradientBoostingRegressor()

In [ ]:
y_pred = model.predict(testing_data[:,0].reshape(-1, 1))
y_pred

array([33.05621077, 82.80773117, 73.60871863, 62.80258768, 85.242871  ,
       62.80258768, 77.29833337, 60.4283958 , 83.40209375, 58.3415076 ,
       83.40209375, 83.40209375, 51.3317227 , 77.88979793, 77.29833337,
       82.80773117, 75.26029188, 72.23701306, 62.80258768, 76.2986538 ,
       51.19104556, 82.80773117, 85.242871  , 73.60871863, 85.242871  ,
       78.9358657 , 79.11953733, 78.9358657 , 68.91225498, 33.05621077])

In [1]:
import numpy as np
from sklearn import preprocessing

In [3]:
x = np.array([[1., -1., 2.],
              [2., 0., 0.],
              [0., 1., -1.]])

In [4]:
x_scaled = preprocessing.scale(x)
x_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [6]:
x_scaled.mean(axis=0)

array([0., 0., 0.])

In [7]:
x_scaled.std(axis=0)

array([1., 1., 1.])

In [9]:
scalar = preprocessing.StandardScaler()
scalar.fit(x)
scalar.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [10]:
x_test = [[1,2,1]]
scalar.transform(x_test)

array([[0.        , 2.44948974, 0.53452248]])

In [13]:
data = [[0,3], [9, 4], [2, 7],[1, 1]]
scaler = preprocessing.StandardScaler()
scaler.fit(data)
first = scaler.transform(data)
second = scaler.transform([[2,13], [1,4], [10,7], [1,9]])
print(first.sum())
print(second.sum())

0.0
8.879529301279849
