In [ ]:
import numpy as np
List = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
x = np.array(List)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
arr = [0,0,0,0,1,0,0,0,0,0]
x = np.array(arr)
for i in x :
    print(i, end=' ')

0 0 0 0 1 0 0 0 0 0 

In [ ]:
import numpy as np
x = np.arange(9,50) 
for i in x :
    print(i, end=' ')

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

In [ ]:
import numpy as np
x = np.eye(5,6, dtype = int)
print(x)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [ ]:
np.random.rand()

0.5965400226655826

In [ ]:
import numpy as np
x = np.linspace(0, 5, 10)
for i in range(1,9) :
    print('%.2f'%x[i])

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [ ]:
arr = [[1,2,3,4], [5,1,12,6], [8,7,5,10], [23,14,9,7]]
arr_np = np.array(arr)
print(arr_np.data)
print(arr_np.shape)
print(arr_np.dtype)
print(arr_np.strides)

(4, 4)
int64
(32, 8)


In [ ]:
import numpy as np
input_2D = np.arange(1,21,1)
input_2D = input_2D.reshape(4,5)
x = input_2D[2, :3]
for i in x :
    print(i, end=' ')
print()

y = input_2D[1: , 3]
for i in y :
    print(i, end=' ')
print()

z = input_2D[2:,]
for i in range(2) :
    for j in range(5) :
        print(z[i][j], end=' ')
print()

a = input_2D[1:3 , 1:3]
for i in range(2) :
    for j in range(2) :
        print(a[i][j], end=' ')
print()

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 


In [ ]:
a = np.random.randint(1, 20, 5)
b = np.random.randint(5, 30, 5)
print(a)
print(b)
print(a+2)
print(a+b)
print(a*b)
print(a/b)

[ 2 18  3 13 19]
[15  8 28 29 14]
[ 4 20  5 15 21]
[17 26 31 42 33]
[ 30 144  84 377 266]
[0.13333333 2.25       0.10714286 0.44827586 1.35714286]


In [ ]:
print(b.min())
print(b.mean())
print(b.argmin())
print(b.sum())
print(a>b)

8
18.8
1
94
[False  True False False  True]


In [ ]:
print(np.logical_and(a, b))
print(np.logical_or(a, b))
print(np.logical_not(a))

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


In [ ]:
x = np.random.randint(4, 36, 8)
print(x)
bool_y = (x>15)
print(bool_y)
y = x[bool_y]
print(y)

[21 17 23 17 18 21 10 28]
[ True  True  True  True  True  True False  True]
[21 17 23 17 18 21 28]


In [ ]:
x[x>=17] = 29
print(x)

[29 29 29 29 29 29 10 29]


In [ ]:
ind = np.where(x<15)
print(ind)

(array([6]),)


In [ ]:
import numpy as np
Li = [1,2,0,0,4,0]
arr = np.array(Li)
ind = np.where(arr != 0) 
for i in range(len(ind)) :
    for j in range(len(ind[0])) :
        print(ind[i][j], end=' ')

0 1 4 

In [ ]:
import numpy as np
Li = [ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
arr = np.array(Li)
ind = np.where(arr%3==0)
for i in range(len(ind)) :
    for j in range(len(ind[0])) :
        print(ind[i][j], end=' ')


1 4 7 

In [ ]:
import numpy as np
Li = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = np.array(Li)
arr[arr%2!=0] = -1
for i in arr :
    print(i, end=' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

In [ ]:
import numpy as np
Li = [11, 2, 13, 4, 15, 6, 27, 8, 19]
arr = np.array(Li)
MAX = arr.max()
arr[arr==MAX] = 0
for i in arr :
    print(i, end=' ')

11 2 13 4 15 6 0 8 19 

In [ ]:
import numpy as np
Li = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = np.array(Li)
Cond = (arr>2) & (arr<9)
arr[Cond] *= -1 
for i in arr :
    print(i, end=' ')

1 2 -3 -4 -5 -6 -7 -8 9 10 

In [ ]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

ind = np.where(height>155)
x = ind[0]
for i in x :
    print(age[i], height[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


In [ ]:
a = np.random.randint(5,45,(5,6))
print(a)
a_bool = (a>21)
print(a_bool)

[[25 42 13 26 16  7]
 [ 5  9 10 11 17 16]
 [32 27 10 23 21  6]
 [18 20 40 14 40  7]
 [13  9 42 31 14 14]]
[[ True  True False  True False False]
 [False False False False False False]
 [ True  True False  True False False]
 [False False  True False  True False]
 [False False  True  True False False]]


In [ ]:
print(a[a_bool])

[25 42 26 32 27 23 40 40 42 31]


In [ ]:
import numpy as np
Li_2d =  [[21, 20, 19, 18, 17],[16, 15, 14, 13, 12],[11, 10,  9,  8,  7],[ 6,  5,  4,  3,  2]]
arr = np.array(Li_2d)

Sorted = arr[np.argsort(arr[:, 1])]
print(Sorted)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [ ]:
import numpy as np
from google.colab import files
uploaded = files.upload()

Saving year2017.csv to year2017.csv


In [ ]:
import csv 
with open('year2017.csv') as Tdata :
    data = csv.DictReader(Tdata, skipinitialspace = True)
    listData = list(data)

Killed = []
Wounded = []
Country = []
for row in listData :
    Killed.append(row['Killed'])
    Wounded.append(row['Wounded'])
    Country.append(row['Country'])

np_Killed = np.array(Killed)
np_Wounded = np.array(Wounded)

np_Killed[np_Killed == ''] = '0.0'
np_Wounded[np_Wounded == ''] = '0.0'

np_Killed = np.array(np_Killed, dtype = float)
np_Wounded = np.array(np_Wounded, dtype = float)

Killed_Wounded = np_Killed + np_Wounded
np_Country = np.array(Country)

bool_arr = np_Country == 'India'

x = Killed_Wounded[bool_arr]

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving terrorismData.csv to terrorismData.csv


In [ ]:
import numpy as np
import csv 
with open("terrorismData.csv",'r',encoding='ISO-8859-1') as file_obj:
    file_data=csv.DictReader(file_obj)
    killed=[]
    
    for row in file_data:
        if row["Country"]=='United States':
            killed.append(row["Killed"])
            
arr_killed=np.array(killed)
arr_killed[arr_killed==""]='0.0'
ar_killed=np.array(arr_killed,dtype=float)  # array is type casted to float 

for row in ar_killed:
    print(int(row), end=' ')

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 4 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [ ]:
import numpy as np
import csv 
with open("terrorismData.csv",'r',encoding='ISO-8859-1') as file_obj:
    file_data=csv.DictReader(file_obj)
    killed=[]
    
    for row in file_data:
        if row["Country"]=='United States':
            killed.append(row["Killed"])
            
arr_killed=np.array(killed)
arr_killed[arr_killed==""]='0.0'
ar_killed=np.array(arr_killed,dtype=float)  # array is type casted to float 

ar_killed = np.array(ar_killed, dtype = int)
print(sum(ar_killed))

3771


In [ ]:
import numpy as np
import csv 
with open("terrorismData.csv",'r',encoding='ISO-8859-1') as file_obj:
    file_data=csv.DictReader(file_obj)
    days=[]
    for row in file_data:
        days.append(row['Day'])
    np_days = np.array(days, dtype=float)
    s = np_days[(np_days>=10) & (np_days<=20)]
print(s.shape[0])

66330


In [ ]:
import numpy as np
import csv 
with open("terrorismData.csv",'r',encoding='ISO-8859-1') as file_obj:
    file_data=csv.DictReader(file_obj)
    
    day=[]
    year=[]
    month=[]
    count=0
    
    for row in file_data:
        day.append(row['Day'])
        month.append(row['Month'])
        year.append(row['Year'])
        
    np_day=np.array(day, dtype='int')
    np_year=np.array(year, dtype='int')
    np_month=np.array(month, dtype='int')
    
    np_day=np_day[np_month == 1 ]
    np_year=np_year[np_month==1]
    np_day=np_day[np_year==2010]
    
    for i in np_day:
        if i>=1 and i<=31:
            count+=1
    print(count)

271


In [ ]:
import numpy as np
import csv
with open("terrorismData.csv",'r',encoding='ISO-8859-1') as file_obj:
    file_data = csv.DictReader(file_obj)
    listData = list(file_data)
killed = []
wounded = []
month = []
year = []
city = []
group = []

for row in listData :
    if "1999" in row["Year"] :
        if "5" in row["Month"] or  "6" in row["Month"] or "7" in row["Month"] :
            if "Unknown" not in row["City"]:
                if "Unknown" not in row["Group"]:
                    if "Jammu and Kashmir" in row["State"]:
                        killed.append(row["Killed"])
                        wounded.append(row["Wounded"])
                        city.append(row["City"])
                        group.append(row["Group"])

np_killed=np.array(killed)
np_wounded=np.array(wounded)

np_killed[np_killed=='']='0'
np_wounded[np_wounded=='']='0'

np_killed=np.array(np_killed, dtype='float')
np_wounded=np.array(np_wounded, dtype='float')

casualty = (killed + wounded)
max_casualty = (int)(casualty.max())
max_casualty_arg = casualty.argmax()
print(max_casualty,city[max_casualty_arg],group[max_casualty_arg])

22 Kargil District Separatists


In [ ]:
import numpy as np
import csv
with open("terrorismData.csv",'r',encoding='ISO-8859-1') as file_obj:
    file_data = csv.DictReader(file_obj)
    listData = list(file_data)

killed = []
wounded = []
state = []
count = 0
for row in listData :
    killed.append(row["Killed"])
    wounded.append(row["Wounded"])
    state.append(row['State'])

np_killed = np.array(killed)
np_wounded = np.array(wounded)

np_killed[np_killed==""] = '0'
np_wounded[np_wounded==""] = '0'

np_killed = np.array(np_killed, dtype = float)
np_wounded = np.array(np_wounded, dtype = float)
np_casuality=np.array(np_killed+np_wounded, dtype='int')

for i in range(len(state)):
    if state[i]=='Chhattisgarh' or state[i]=='Odisha' or state[i]=='Jharkhand' or state[i]=='Andhra Pradesh':
        count+=np_casuality[i]
print(count)

5628


In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
import csv
with open("terrorismData.csv") as csvData :
    data = csv.DictReader(csvData, skipinitialspace = True) 
    listData = list(data)

killed = []
wounded = []
city = []
count = 0
for row in listData :
    if "India" in row["Country"] and "Unknown" not in row["City"] :
        city.append(row["City"])
        killed.append(row["Killed"])
        wounded.append(row["Wounded"])
np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_city = np.array(city)

np_killed[np_killed==""] = '0'
np_wounded[np_wounded==""] = '0'

np_killed = np.array(np_killed, dtype=float)
np_wounded = np.array(np_wounded, dtype=float)
np_casuality = np.array(np_killed+np_wounded, dtype=int)

cityDict = {}
for i in range(len(np_city)) :
    if np_city[i] in cityDict :
        cityDict[np_city[i]] += np_casuality[i]
    else :
        cityDict[np_city[i]] = np_casuality[i]

count=0
city=''
for i in cityDict:
    if cityDict[i]>count:
        count=cityDict[i]
        city=i
print(city, count)
del cityDict[city]

count=0
city=''
for i in cityDict:
    if cityDict[i]>count:
        count=cityDict[i]
        city=i
print(city, count)
del cityDict[city]

count=0
city=''
for i in cityDict:
    if cityDict[i]>count:
        count=cityDict[i]
        city=i
print(city, count)
del cityDict[city]

count=0
city=''
for i in cityDict:
    if cityDict[i]>count:
        count=cityDict[i]
        city=i
print(city, count)
del cityDict[city]

count=0
city=''
for i in cityDict:
    if cityDict[i]>count:
        count=cityDict[i]
        city=i
print(city, count)
del cityDict[city]

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


In [ ]:
import numpy as np 
import csv
with open('terrorismData.csv', encoding='utf8') as csvData :
    data = csv.DictReader(csvData, skipinitialspace= True)
    
    day=[]
    for row in data :
        day.append(row['Day'])
    np_day=np.array(day, dtype='int')
    day, count=np.unique(np_day, return_counts=True)
    print(day[np.argmax(count)], count[np.argmax(count)])

15 6500
