In [ ]:
import numpy as np
Li = [4,5,6,8,9,2,10,1,2,2,35,6]
b = np.random.randint(2,40,12)
print(b)
arr = np.array(Li)
print(arr)
print(Li[3])
print(arr[3])
print(arr[1:6])
print(arr.max())
print(arr.argmin()) # arr.mean(), arr.median()
print(arr>b) # both array should have same shape
print(b[b>20]) # no which are greater than 20
print(np.where(b[b<18]))
ind = np.where(arr<8)
print(b[ind])

[ 2 34 16 29 31 38 33 22 12 15 25 11]
[ 4  5  6  8  9  2 10  1  2  2 35  6]
8
8
[5 6 8 9 2]
35
7
[ True False False False False False False False False False  True False]
[34 29 31 38 33 22 25]
(array([0, 1, 2, 3, 4]),)
[ 2 34 16 38 22 12 15 11]


In [ ]:
Li_2d = [[2,5,9,8,6,12,10],[6,2,-8,5,10,25,20],[4,2,5,6,8,7,-10],[10,4,13,6,8,9,15],[12,14,17,8,5,24,10]]
arr_2d = np.array(Li_2d)
print(arr_2d)
print(Li_2d[3][4])
print(arr_2d[3][4])
print(arr_2d[3, 4])
print(Li_2d[0:3][2]) # here we are getting 1st three lists and we are accesing 2 nd element of that list
print(arr_2d[0:3, 3]) # here we are doing slicing
print(arr_2d[2:4, 1:4])

[[  2   5   9   8   6  12  10]
 [  6   2  -8   5  10  25  20]
 [  4   2   5   6   8   7 -10]
 [ 10   4  13   6   8   9  15]
 [ 12  14  17   8   5  24  10]]
8
8
8
[4, 2, 5, 6, 8, 7, -10]
[8 5 6]
[[ 2  5  6]
 [ 4 13  6]]


In [ ]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

p = input_[2, 0:3]
for i in p:
  print(i,end=' ')
print('\n')  
q = input_[1:4, 3]
for i in q:
  print(i,end=' ')
print('\n')   
r = input_[2:4]
for i in r:
    for j in i:
      print(j,end=' ')
print('\n')   
s = input_[1:3, 1:3]
for i in s:
  for j in i:
      print(j,end=' ')

11 12 13 

9 14 19 

11 12 13 14 15 16 17 18 19 20 

7 8 12 13 

In [ ]:
import numpy as np
a = [1,2,0,0,4,0]
x = np.array(a)
ind = np.where(x>0)
for i in ind:
    for j in i:
        print(j, end=' ')

0 1 4 

In [ ]:
import numpy as np
a = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19])
ind = np.where(a%3==0)
for i in ind:
    for j in i:
        print(j, end=' ')

1 4 7 

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a%2!=0] = -1
for i in a:
  print(i,end=' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

In [ ]:
import numpy as np
a = np.array([11,2,13,4,15,6,27,8,19])
m = np.max(a)
a = np.where(a==m, 0, a)
for i in a:
  print(i,end=' ')

11 2 13 4 15 6 0 8 19 

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
m = (a > 2) & (a < 9)
a[m] *= -1
for i in a:
  print(i,end=' ')

1 2 -3 -4 -5 -6 -7 -8 9 10 

In [ ]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

ind = np.where(height>155)
for i in ind[0]:
    print(age[i], end = " ")
    print(height[i])
    

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


In [ ]:
x = np.random.randint(2,40, (4,5))
print(x)
p =x[x > 20]
print(p)

[[25 10  8 12 17]
 [16 24  5 19  3]
 [16 29 25 19 28]
 [ 6  9 37 17 22]]
[25 24 29 25 28 37 22]


In [ ]:
x_bool = x[:,2] > 20 
x[x_bool, 2] = 18
print(x) 


[[25 10  8 12 17]
 [16 24  5 19  3]
 [16 29 18 18 28]
 [ 6  9 18 18 22]]


In [ ]:
import numpy as np
a = np.array([[21, 20, 19, 18, 17],
              [16, 15, 14, 13, 12],
              [11, 10,  9,  8,  7],
              [ 6,  5,  4,  3,  2]])
c = 0
a = a[np.argsort(a[:,c])]
print(a)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [ ]:
x = np.random.randint(2,20, (4,4))
y = np.random.randint(2,20, (4,4))
print(x)
print(y)
print(x-y)

[[ 8 11 17  2]
 [15 17 17 16]
 [15  5  8  2]
 [18 16 10  5]]
[[ 7  6  3 15]
 [ 9  9  5 16]
 [ 5  2 17 17]
 [19 16 19 12]]
[[  1   5  14 -13]
 [  6   8  12   0]
 [ 10   3  -9 -15]
 [ -1   0  -9  -7]]


In [ ]:
z = np.random.randint(2,25, (4)) # by broadcasting the same array of size 4 repeated 4 times to perform operation
print(x-z) # dont give any error

#resize(), reshape() are used to make element by element operation more compatible

[[  4   1   8 -14]
 [ 11   7   8   0]
 [ 11  -5  -1 -14]
 [ 14   6   1 -11]]


In [ ]:
import numpy as np
x = np.linspace(0,5,10,dtype=float)
y = np.around(x,2)

for i in y[1:9]:
    print(i,end=' ')


0.56 1.11 1.67 2.22 2.78 3.33 3.89 4.44 

In [ ]:
import numpy as np
def Identity(m,n):
    for row in range(0, m):
        for col in range(0, n):
 
            # Here end is used to stay in same line
            if (row == col):
                print("1 ", end=" ")
            else:
                print("0 ", end=" ")
        print()

Identity(5,6)    

1  0  0  0  0  0  
0  1  0  0  0  0  
0  0  1  0  0  0  
0  0  0  1  0  0  
0  0  0  0  1  0  


In [ ]:
import numpy as np
x = np.eye(5,6, dtype=int)
print(x)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]
